# netlify.toml
[build]
  # This command will execute app.py, which calls freezer.freeze()
  # to generate your static site into the 'build' directory.
  command = "python app.py"
  # This is the directory where Flask-Frozen outputs the static files.
  publish = "build"

# Optional: If you want to redirect all unknown paths to index.html (for single-page apps or clean URLs)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

